# Generated by Django 4.0.6 on 2022-12-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_employeemodel_date_registered'),
        ('employee', '0002_alter_applyleave_id_alter_applyleave_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='user',
        ),
        migrations.AddField(
            model_name='applyleave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.employeemodel'),
        ),
    ]
