# Generated by Django 4.0.6 on 2022-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_applyleave_user_applyleave_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
