# Generated by Django 4.0.6 on 2022-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_applyleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='total_leave',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
