# Generated by Django 4.0.6 on 2022-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_user_category_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
