# Generated by Django 4.0.6 on 2022-12-23 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_user_profile_alter_employeemodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
