# Generated by Django 4.1.3 on 2022-12-25 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_employeemodel_date_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='profile',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
