# Generated by Django 4.1.3 on 2022-12-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_remove_employeemodel_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='profile',
            field=models.ImageField(blank=True, default='profile_pic/admin.png', upload_to='profile_pic'),
        ),
    ]
