# Generated by Django 4.1.3 on 2022-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_employeemodel_profile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
