# Generated by Django 4.0.6 on 2022-12-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('days_allowed', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
