# Generated by Django 4.0.6 on 2022-12-27 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
