# Generated by Django 4.0.6 on 2022-12-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_leavetype_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
    ]
