# Generated by Django 4.0.6 on 2022-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_department_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
